### ISSUE TITLE
Filter Modal Bugs

### ISSUE THREAD

**Issue by smaraghi** [CSIS-iLab/energy-jti#58]
### Filter-Modal Bugs
- [x] Dropdowns resize as you check of checkboxes breaking their styling and the styling of buttons and dropdowns in the grid layout. 
- [x] Click on the tabs multiple tabs then opening the modal produces several checkboxes
- [ ] Increment num filters as they're applied in the modal (low priority)
- [x] Can't click on both child & parent options in Focus Areas section

- [x] Add max-width 550px to &__date-range to keep custom date range dropdowns from breaking on larger screen widths

- [x] Header styling is wrong on ipad, mobile

**Comment by jnschrag** [comment]
@smaraghi I'm going to close this in favor of the aggregated bugs list.
