### ISSUE TITLE
Component: Post-Block

### ISSUE THREAD

**Issue by smaraghi** [CSIS-iLab/energy-jti#9]
### Post Block
<img width="644" alt="Screen Shot 2020-10-08 at 4 50 41 PM" src="https://user-images.githubusercontent.com/45780666/95512319-aa28cb80-0986-11eb-93d5-ea9545391a03.png">

- [x] Image
- [x] Type of Post
- [x] Title
     - [x] Link to Post
- [x] Publication Date
- [x] Description

Layout is different for Post Block on HomePage:

<img width="433" alt="Screen Shot 2020-10-08 at 4 56 29 PM" src="https://user-images.githubusercontent.com/45780666/95512839-6c787280-0987-11eb-85a0-3154de0c6ea9.png">

**Comment by jnschrag** [comment]
Heads up that the post block on the home page is now the same as it is on the archives.
